services:
  backend:
    build: ./backend
    container_name: plantcare_backend
    ports:
      - "4000:4000"       # backend berjalan di port 4000
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: ""
      DB_NAME: plantcare
      DB_PORT: 5432

  db:
    image: postgres:15
    container_name: plantcare_db
    ports:
      - "5433:5432"     # host 5433 â†’ container 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: plantcare
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - plantcare_dbdata:/var/lib/postgresql/data

volumes:
  plantcare_dbdata:
